name: QMK firmware build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard:
          - kinesis/stapelberg

    steps:
    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
        submodules: recursive
        persist-credentials: false

    - name: Checkout userspace
      uses: actions/checkout@v3
      with:
        path: users/${{ github.actor }}
        persist-credentials: false
    
    # - name: Symlink userspace
    #   run: ln -s users/${{ github.actor }} keyboards/users/${{ github.actor }}

    - name: Build firmware
      run: qmk compile -kb kinesis/stapelberg

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: ${{ matrix.keyboard }}_${{ github.run_number }}
        path: |
          *.hex
          *.bin
          *.uf2
