name: QMK firmware build
on: [push, workflow_dispatch]

jobs:
  build-firmware:
    name: Build QMK firmware
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
      - name: Disable git safe directory checks
        run: git config --global --add safe.directory '*'

      - name: Checkout QMK
        uses: actions/checkout@v3
        with:
          repository: qmk/qmk_firmware
          submodules: recursive
          persist-credentials: false

      - name: Checkout userspace
        uses: actions/checkout@v3
        with:
          path: ${{ github.actor }}
          persist-credentials: false

      - name: Symlink keymap from userspace to qmk directory
        run: |
          ln -s ../../../${{ github.actor }}/keymap_kinesis keyboards/kinesis/keymaps/${{ github.actor }}
          ln -s ../../../${{ github.actor }}/keymap_keychron_q2 keyboards/keychron/q2/ansi_encoder/keymaps/${{ github.actor }}

      - name: Build firmware
        run: |
          mkdir dist
          qmk compile -kb kinesis/stapelberg -km ${{ github.actor }}
          qmk c2json -kb kinesis/stapelberg -km hadynz keyboards/kinesis/keymaps/${{ github.actor }}/keymap.c > keymap_kinesis.json

          qmk compile -kb keychron/q2/ansi_encoder -km ${{ github.actor }}
          qmk c2json -kb keychron/q2/ansi_encoder -km hadynz keyboards/keychron/q2/ansi_encoder/keymaps/${{ github.actor }}/keymap.c > keymap_keychron_q2.json

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: qmk-firmware-artifact-${{ github.run_number }}
          path: |
            *.hex
            *.json

  render-keymap:
    name: Render keymap
    needs: [build-firmware]
    runs-on: ubuntu-latest
    steps:
      - name: Download firmware build file
        uses: actions/download-artifact@v2
        with:
          name: qmk-firmware-artifact-${{ github.run_number }}

      - name: Install keymap-drawer
        run: python3 -m pip install keymap-drawer
      
      - name: Draw keymap and package        
        run: |
          ls -la
          keymap parse -c 10 -q keymap.json > keymap.yaml
          keymap draw keymap.yaml > keymap.svg
          ls -la

      - name: Upload rendered keymap
        uses: actions/upload-artifact@v3
        with:
          name: qmk-firmware-artifact-${{ github.run_number }}
          path: |
            *.svg
            *.json
