name: QMK firmware build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard:
          - hadynz-kinesis

    steps:
    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
        submodules: recursive

    - name: Checkout userspace
      uses: actions/checkout@v3
      with:
        path: users/${{ github.actor }}

    - name: Add keyboards
      run: |
        for keyboard_folder in users/${{ github.actor }}/keyboards/*; do
          ln -s $(realpath $keyboard_folder) keyboards/
        done

    - name: Build firmware
      run: qmk compile "users/${{ github.actor }}/keymaps/${{ matrix.keyboard }}.json"

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: ${{ matrix.keyboard }}_${{ github.run_number }}
        path: |
          *.hex
          *.bin
          *.uf2
